### ISSUE TITLE
Comentário sobre o trabalho

### ISSUE THREAD

**Issue by fccoelho** [julymartins3/Trabalho-Final-MM4#1]
Muito boa aapresentação @Caioflp!  ficou muito clara a descrição do modelo!
Parabéns também pela compreensão da biologia da infeção pelo HIV!
Faltou uma referência na apresentação do artigo no qual vcs basearam o modelo: Poder ser apenas a referência no rodapé do slide.
Acho que a análise das estabilidades dos equilíprios e pontos de bifurácão associados o surgimento de variantes e da introdução do tratamento pode ficar bem interessante.

Vocês chegaram a pensar que esta dinâmica de surgimento de variantes é análoga ao que vemos na dinâmica do SARS-CoV-2?
E que a Vacinação representa uma pressão seletiva similar ao do tratamento?

Continuem investindo no trabalho. Se quiserem seguir isto para o TCC posso apresentar vocês a um amigo meu que é virologista e poderia orienta a aplicação do que vocês aprenderam a um problema mais atual.

**Comment by Caioflp** [comment]
Muito obrigado pelo comentário, Professor! Vamos refletir sobre as questões que você propôs.

Quanto ao TCC, eu a Juliane vamos pensar mais a respeito e te damos um retorno.

Se tivermos alguma dúvida, abriremos uma issue.

Abraços!
